[features]
seeds = false
skip-lint = false
[programs.devnet]
rewards_portal = "Eebaw3MaCuRBKPaAVe3bSWk8kJd99e77YoENumo2ZgSD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./solana/id.json"

[scripts]
test = "node tests/rewards-portal.js"
